"use client";

import { useState } from "react";
import { useProposalStore } from "@/store/proposalStore";
import { formatCurrency, formatRupiah } from "@/lib/format";

export function OutputPanel() {
  const input = useProposalStore((s) => s.input);
  const output = useProposalStore((s) => s.output);
  const [currencyMode, setCurrencyMode] = useState<"compact" | "full" | "juta">("compact");
  const doctrineLabel =
    input.discipline === "planning"
      ? "Master Planning (Per Hectare)"
      : input.discipline === "building"
        ? "Architecture (Per SQM)"
        : `${output.doctrine.toUpperCase()}`;

  return (
    <div className="sticky top-6 ml-auto w-full max-w-[560px] border border-[#EAEAEA] bg-white p-8 shadow-md">
      <div className="space-y-5">
        <h3 className="font-serif text-[34px] leading-[1.1]">{input.projectName || "Untitled Proposal"}</h3>
        <p className="mt-1 text-[12px] uppercase tracking-[0.1em] text-[#6B6B6B]">{doctrineLabel}</p>
        <div className="mt-3 h-px w-16 bg-[#E10600]" />
        <div className="mt-6">
          <p className="text-xs uppercase tracking-[0.3em] text-[#6B6B6B]">Total Professional Fee</p>
          <div
            className="mt-2 text-[46px] font-medium text-[#E10600]"
            style={{ fontFeatureSettings: "\"tnum\" 1" }}
            title={`Full amount: ${formatCurrency(output.totalFee, "full")}`}
          >
            {formatCurrency(output.totalFee, currencyMode)}
          </div>
          <div className="mt-3 flex gap-1.5">
            <button className={`border px-2 py-0.5 text-[10px] transition-opacity ${currencyMode === "compact" ? "border-[#E10600] text-[#E10600] opacity-100" : "border-[#E2E2E2] text-[#6B6B6B] opacity-55"}`} onClick={() => setCurrencyMode("compact")}>M</button>
            <button className={`border px-2 py-0.5 text-[10px] transition-opacity ${currencyMode === "juta" ? "border-[#E10600] text-[#E10600] opacity-100" : "border-[#E2E2E2] text-[#6B6B6B] opacity-55"}`} onClick={() => setCurrencyMode("juta")}>jt</button>
            <button className={`border px-2 py-0.5 text-[10px] transition-opacity ${currencyMode === "full" ? "border-[#E10600] text-[#E10600] opacity-100" : "border-[#E2E2E2] text-[#6B6B6B] opacity-55"}`} onClick={() => setCurrencyMode("full")}>Full</button>
          </div>
        </div>
        <div className="border-t border-[#EAEAEA] pt-4">
          <h3 className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-[#6B6B6B]">Fee Breakdown</h3>
          <div className="space-y-2">
            {[
              { label: "Base Fee", value: output.baseFee },
              { label: "Complexity Adjustment", value: output.complexityAdjustment },
              { label: "Engagement Activation", value: output.engagementCost },
              { label: "Travel Cost", value: output.travelCost },
              { label: "Visualization Fees", value: output.visualizationCost },
            ].map((row) => (
              <div key={row.label} className="flex items-center justify-between text-sm">
                <span className="text-[#6B6B6B]">{row.label}</span>
                <span className="tabular-nums font-semibold">{formatRupiah(row.value)}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="border-t border-[#EAEAEA] pt-4">
          <h3 className="text-xs font-bold uppercase tracking-[0.2em] text-[#6B6B6B]">Phase Breakdown</h3>
          <div className="mt-3 space-y-2">
            {output.phaseBreakdown.map((phase) => (
              <div key={phase.phase} className="flex justify-between text-sm">
                <span>{phase.phase} ({phase.percentage}%)</span>
                <span className="tabular-nums font-semibold">{formatRupiah(phase.amount)}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="border-t border-[#EAEAEA] pt-4 text-sm">
          <p>Duration estimate: <strong>{output.durationMonths} months</strong></p>
          <p className="mt-2">
            Suggested team allocation: <strong>SNR {output.suggestedTeamAllocation.snr}</strong>, <strong>MID {output.suggestedTeamAllocation.mid}</strong>, <strong>JNR {output.suggestedTeamAllocation.jnr}</strong>
          </p>
        </div>

        <div className="pt-6 text-right text-[10px] text-[#6B6B6B]/70">
          <div>Generated by AIM + HDA</div>
          <div>Powered by Kolabs.Design</div>
        </div>
      </div>
    </div>
  );
}
